# Generated by Django 5.1.2 on 2024-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('species', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('D', 'Dragon'), ('O', 'Ogre'), ('F', 'Fairy'), ('FI', 'Fish'), ('S', 'Slime')], default='D', max_length=2)),
                ('color', models.CharField(max_length=20)),
                ('passive', models.CharField(max_length=30)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
    ]
