# Generated by Django 5.1.2 on 2024-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_description', models.CharField(max_length=50)),
                ('special', models.CharField(choices=[('P', 'Punch'), ('K', 'Kick'), ('S', 'Suffocation'), ('F', 'Fire Claw'), ('W', 'Wet Body'), ('SH', 'Shadow Ball'), ('FB', 'Fire Ball'), ('H', 'Holy'), ('G', 'Grass Knot'), ('S', 'Slam')], default='P', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='monster',
            name='passive',
            field=models.CharField(choices=[('S', 'Sleepy'), ('F', 'Fury'), ('N', 'Nimble')], max_length=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='moves',
            field=models.ManyToManyField(to='main_app.moves'),
        ),
    ]
